pipeline:
  build:
    image: node:8.9
    commands:
      - npm install
      - npm test
  docker:
    image: plugins/docker
    repo: my-docker-registry:5000/auto-build-node
    tags: latest
    dockerfile: Dockerfile
    registry: my-docker-registry:5000
