pipeline:
  build:
    image: node:8.9
    commands:
      - npm install
      - npm test
  monit:
    image: docker
    commands:
      - echo "ci_tag ${CI_TAG}"
      - echo DRONE_TAG ${DRONE_TAG}
      - echo DRONE_BUILD_NUMBER ${DRONE_BUILD_NUMBER}
      - echo DRONE_COMMIT_REF ${DRONE_COMMIT_REF}
      - echo DRONE_COMMIT_BRANCH ${DRONE_COMMIT_BRANCH}

  docker:
    image: plugins/docker
    repo: ead4dcaa.ap.ngrok.io/auto-build-node
    secrets: [ docker_username, docker_password ]
    tags: ["latest", "${DRONE_COMMIT_BRANCH}", "${##v}"]
    dockerfile: Dockerfile
    registry: ead4dcaa.ap.ngrok.io