pipeline:
  build:
    image: node:8.9
    commands:
      - npm install
      - npm test
  monit:
    image: docker
    commands:
      - echo ${REGISTRY_HOST}
      - echo ${REGISTRY_USER}
      - echo ${REGISTRY_PASS}

  docker:
    image: plugins/docker
    repo: c892df72.ap.ngrok.io/auto-build-node
    secrets: [ docker_username, docker_password ]
    tags: latest
    dockerfile: Dockerfile
    registry: c892df72.ap.ngrok.io