pipeline:
  build:
    image: node:8.9
    commands:
      - npm install
      - npm test
  build-image:
    image: docker
    commands:
      - docker build --rm -t docker-registry:5000/auto-build-node .